import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import "../globals.css";
import Script from "next/script";
import { Toaster } from "react-hot-toast";
import Header from "../components/header";
import Footer from "../components/footer";
import Providers from "../providers";
import { use } from "react";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Ngolion Fidely",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"]
})

export default function RootLayout({
  children,
  params
 }: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
 }) {
  const { locale } = use(params);
  return (
    <html lang={locale} className="scroll-smooth">
      <head>
     
        <link rel="icon" type="image/png" sizes="192x192" href="/images/logo/android-chrome-192x192.png" />
        <link rel="icon" type="image/png" sizes="512x512" href="/images/logo/android-chrome-512x512.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/images/logo/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/images/logo/favicon-16x16.png" />
        <link rel="icon" href="/favicon.ico" />

        
        <link rel="apple-touch-icon" sizes="180x180" href="/images/logo/apple-touch-icon.png" />
        <meta name="apple-mobile-web-app-title" content="Ngolion Fidely" />
          <Script
          src="https://kit.fontawesome.com/c44b1437e7.js"
          crossOrigin="anonymous"
        />
        <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/3.0.0/uicons-solid-straight/css/uicons-solid-straight.css' />
        <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/3.0.0/uicons-solid-rounded/css/uicons-solid-rounded.css' />
        <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/3.0.0/uicons-regular-rounded/css/uicons-regular-rounded.css' />
      </head>
      <body
        className={poppins.className}
      >
        <Providers>
        <main>{children}</main>
        <Toaster position="top-right" reverseOrder={false} />
        </Providers>
      </body>
    </html>
  );
}






// import Providers from "../providers";

// export default function LocaleLayout({
//   children,
//   params: { locale }
// }: {
//   children: React.ReactNode;
//   params: { locale: string };
// }) {
//   return (
//     <html lang={locale}>
//       <body>
//         <Providers>{children}</Providers>
//       </body>
//     </html>
//   );
// }


